export const characters = [
  {
    name: "Eric Cartman",
    gender: "male",
    age: 10,
    hair: "brown",
    desc: `Eric Theodore Cartman, usually referred to as just Cartman, is one of the main characters, along with Stan Marsh, Kyle Broflovski, and Kenny McCormick. Cartman is sometimes the main antagonist of an episode, for example "Trapper Keeper". None of the other three main children really consider Cartman their friend and do not know why they started hanging out with him in the first place, but a certain form of unstable friendship ends up being born between them. However he is usually Kyle's first choice when he breaks his friendship with Stan. In earlier episodes, Kenny was his best friend, however, in later seasons, Butters Stotch is usually depicted as such.`,
    img: "./public/img/cartman.jpg",
  },
  {
    name: "Stan Marsh",
    gender: "male",
    age: 10,
    hair: "black",
    desc: `Stanley Stan Marsh is one of South Park's main characters along with Kyle Broflovski, Eric Cartman, and Kenny McCormick. Stan attends South Park Elementary as part of Mr. Garrison's Fourth Grade Class (formerly Third). Stan's father Randy is a geologist, and his mother Sharon is a secretary at Tom's Rhinoplasty. He briefly had a step-father in "Clubhouses", named Roy. Since its beginning, the series has had a running gag where when Kenny is killed, Stan will announce, "Oh my God, they killed Kenny!" Kyle will then respond: "Those bastards!", or vice versa. Stan's often-used catchphrase during the early seasons was "Dude, this is pretty fucked up right here," which originated in the second The Spirit of Christmas short, though the profanity was bleeped out. In recent episodes, however this catchphrase has faded.`,
    img: "./img/stan.jpg",
  },
  {
    name: "Kyle Broflovski",
    gender: "male",
    age: 10,
    hair: "red",
    desc: `Kyle Broflovski is one of South Park's main characters, along with Stan Marsh, Eric Cartman, and Kenny McCormick. Based on co-creator Matt Stone, Kyle is a member of the only Jewish family in South Park. He is often noted for this, as well as his intelligence. Kyle is of the Jewish faith, but this detail is not officially revealed until "Mr. Hankey, the Christmas Poo", despite having been mentioned briefly in the second The Spirit of Christmas short, and in "Big Gay Al's Big Gay Boat Ride". It was also mentioned in "An Elephant Makes Love to a Pig". Cartman regularly makes derogatory remarks about the Jewish people, often directly in Kyle's presence specifically to aggravate him.`,
    img: "./img/kyle.jpg",
  },
  {
    name: "Kenny McCormick",
    gender: "male",
    age: 10,
    hair: "blond",
    desc: `Kenneth "Kenny" McCormick, voiced by Matt Stone, is one of South Park's main characters, along with Eric Cartman, Stan Marsh, and Kyle Broflovski. He first appears in the short films both entitled The Spirit of Christmas in 1992 and 1995. He is voiced by Mike Judge in the feature film South Park: Bigger, Longer & Uncut and Eric Stough in "The Jeffersons", "Lice Capades", "Mysterion Rises", and "Turd Burglars". Kenny is most famous for dying in almost every episode in the first five seasons of South Park. He is also easily recognizable for almost always wearing an orange parka, or just having his face hidden, that covers most of his face and muffles his speech. In "Mysterion Rises" Kenny, who is revealed to be the superhero Mysterion, reveals that he has the power of immortality, in a sense, and that he just wakes up in his bed after having died. He is then upset that his friends never remember him dying, and even kills himself in front of everyone to prove himself.`,
    img: "./img/kenny.jpg",
  },
  {
    name: "Wendy Testaburger",
    gender: "female",
    age: 10,
    hair: "black",
    desc: `Wendy Testaburger is a major-supporting character and the most prominent female character on South Park. She is the most prominent of the female classmates of Stan, Kyle, Cartman and Kenny, as well as Stan's on-and-off girlfriend. Wendy is a female fourth-grade student at South Park Elementary. She made her first appearance and speaking role in the Season One episode "Cartman Gets an Anal Probe". Wendy has been voiced by four people during the series' run: Mary Kay Bergman, Mona Marshall, Eliza J. Schneider and currently April Stewart.`,
    img: "./img/wendy.jpg",
  },
  {
    name: "Butters Stotch",
    gender: "male",
    age: 10,
    hair: "blond",
    desc: `Leopold "Butters" Stotch is a major character in the series. He is a fourth-grader in South Park Elementary. Butters' role gradually began to increase after he replaced Kenny during his temporary removal in Season Six. This allowed Butters to gain more screen time and further develop his character. He is the "innocent child" in the group and Cartman's most exploited and possibly best "friend". Butters is loosely based on Eric Stough, an animation director/producer that works on the show. Butters has made appearances since "Cartman Gets an Anal Probe", though initially as a background character. He gets his first speaking role in the Season Two episode, "Clubhouses". He later receives a speaking role in South Park: Bigger, Longer & Uncut.`,
    img: "./img/butters.jpg",
  },
  {
    name: "Jimmy Valmer",
    gender: "male",
    age: 10,
    hair: "brown",
    desc: `Jimmy Valmer (previously Swanson) is a male fourth grader. He is voiced by Trey Parker. He was originally created as a one-time character for "Cripple Fight" as a rival for Timmy Burch, but he quickly became a fan favorite and plays a supporting role in many episodes. He and Timmy became best friends and less of a rival to one another. Like Timmy, the humor of Jimmy's character comes from his endless optimism despite his handicap. His disability is not overtly mocked; rather his exaggerated eagerness to be a successful "handi-capable" person. Jimmy's role has more recently been expanded, bringing him more screen time and giving his character more depth. In "Professor Chaos", he is one of the final 10 chosen to be their fourth member, but ultimately he is not picked. In later seasons, he is shown hanging with Craig's Gang.`,
    img: "./img/jimmy.jpg",
  },
  {
    name: "Shelley Marsh",
    gender: "female",
    age: 13,
    hair: "brown",
    desc: `Shelley Marsh is Randy and Sharon Marsh's daughter and Stan Marsh's older sister. She is vindictive, aggressive, and extremely ill-tempered, referring to those around her as "turds" and often beating or even torturing Stan when adults are not around, though nonetheless compassionate; later seasons have instead emphasized Shelley as assertive and focused more on her relationship with her father. Shelley has been voiced at different times by Mary Kay Bergman, Eliza Schneider, and currently April Stewart. She first appeared in the Season One episode, "An Elephant Makes Love to a Pig".`,
    img: "./img/shelley.jpg",
  },
  {
    name: "Towelie",
    gender: "male",
    age: 17,
    hair: "brown",
    desc: `Towelie is a talking towel who was genetically engineered by Tynacorp, in order to allow him to make people as dry as necessary depending on the situation. He first appeared in the Season Five episode, "Towelie". He is usually seen either appearing out of nowhere to give towel advice to the citizens of South Park or getting high. The theme song from Popeye plays whenever Towelie gets high. He is also the agricultural inspector and friend of Randy Marsh.`,
    img: "./img/towelie.jpg",
  },
];
